// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Lcars

#ifndef _LCARS_UI_H
#define _LCARS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void ON1_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Background;
extern lv_obj_t * ui_Top_Right;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Center;
extern lv_obj_t * ui_batterie;
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Current1;
extern lv_obj_t * ui_Current;
extern lv_obj_t * ui_labelAmp;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_grpVersorger;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_ueberschriftmain;
extern lv_obj_t * ui_statsmain;
extern lv_obj_t * ui_voltagemain;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_lblvoltagemain;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_capacitymain;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_lblcapacitymain;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_tempmain;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_lbltempmain;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_remainmain;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_lblrmainmain;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_grpMotor;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_ueberschriftmotor;
extern lv_obj_t * ui_statsmotor;
extern lv_obj_t * ui_voltagemaschine1;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_ueberschriftmain3;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_lblvoltagemotor1;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_tempmaschine1;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_lbltempmotor1;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_voltagemaschine2;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_lblvoltagemotor2;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_tempmaschine2;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_lbltempmotor2;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_grpBug;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_ueberschriftbug;
extern lv_obj_t * ui_statsbug;
extern lv_obj_t * ui_voltagebug;
extern lv_obj_t * ui_Panel21;
extern lv_obj_t * ui_ueberschriftmain4;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_lblvoltagebug;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_tempbug;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_lbltempbug;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_buttons;
void ui_event_btnbug(lv_event_t * e);
extern lv_obj_t * ui_btnbug;
extern lv_obj_t * ui_Label4;
void ui_event_btnmotor(lv_event_t * e);
extern lv_obj_t * ui_btnmotor;
extern lv_obj_t * ui_Label3;
void ui_event_btnmain(lv_event_t * e);
extern lv_obj_t * ui_btnmain;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_lblTime;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_imgchargetrans;
extern lv_obj_t * ui_imgcharge;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_socmain;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_batterie_bg_png);    // assets/batterie_bg.png
LV_IMG_DECLARE(ui_img_indicator_bg_png);    // assets/indicator_bg.png
LV_IMG_DECLARE(ui_img_charge_trans_png);    // assets/charge_trans.png
LV_IMG_DECLARE(ui_img_charge_png);    // assets/charge.png
LV_IMG_DECLARE(ui_img_blitz_png);    // assets/blitz.png

// FONTS
LV_FONT_DECLARE(ui_font_Top);
LV_FONT_DECLARE(ui_font_battery);
LV_FONT_DECLARE(ui_font_button);
LV_FONT_DECLARE(ui_font_labelAmp);
LV_FONT_DECLARE(ui_font_sidebar);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
