// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Lcars

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Background = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Background, 547);
    lv_obj_set_height(ui_Background, 269);
    lv_obj_set_align(ui_Background, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Background, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Background, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Background, lv_color_hex(0xFFAA00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Background, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Background, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Background, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Background, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Background, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Top_Right = lv_obj_create(ui_Background);
    lv_obj_set_width(ui_Top_Right, 163);
    lv_obj_set_height(ui_Top_Right, 25);
    lv_obj_set_x(ui_Top_Right, 83);
    lv_obj_set_y(ui_Top_Right, -125);
    lv_obj_set_align(ui_Top_Right, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Top_Right, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Top_Right, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Top_Right, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Top_Right, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Top_Right, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Top_Right, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Top_Right);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, 3);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Batteriemonitor");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Top, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Center = lv_obj_create(ui_Background);
    lv_obj_set_width(ui_Center, 461);
    lv_obj_set_height(ui_Center, 223);
    lv_obj_set_x(ui_Center, 16);
    lv_obj_set_y(ui_Center, -1);
    lv_obj_set_align(ui_Center, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Center, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Center, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Center, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Center, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Center, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Center, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batterie = lv_img_create(ui_Center);
    lv_img_set_src(ui_batterie, &ui_img_batterie_bg_png);
    lv_obj_set_width(ui_batterie, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batterie, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batterie, -41);
    lv_obj_set_y(ui_batterie, 0);
    lv_obj_set_align(ui_batterie, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_batterie, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_batterie, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slider2 = lv_slider_create(ui_batterie);
    lv_slider_set_value(ui_Slider2, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 48);
    lv_obj_set_height(ui_Slider2, 97);
    lv_obj_set_x(ui_Slider2, 0);
    lv_obj_set_y(ui_Slider2, 7);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Slider2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Slider2, &ui_img_indicator_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_Slider2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Slider2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Slider2, &ui_img_indicator_bg_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_Slider2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Current1 = lv_obj_create(ui_Center);
    lv_obj_remove_style_all(ui_Current1);
    lv_obj_set_width(ui_Current1, 93);
    lv_obj_set_height(ui_Current1, 100);
    lv_obj_set_x(ui_Current1, -103);
    lv_obj_set_y(ui_Current1, 0);
    lv_obj_set_align(ui_Current1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Current1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Current = lv_label_create(ui_Current1);
    lv_obj_set_width(ui_Current, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Current, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Current, "Current");
    lv_obj_set_style_text_font(ui_Current, &ui_font_sidebar, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelAmp = lv_label_create(ui_Current1);
    lv_obj_set_width(ui_labelAmp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelAmp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelAmp, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_labelAmp, &ui_font_labelAmp, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Current1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Label6, "A");
    lv_obj_set_style_text_font(ui_Label6, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_grpVersorger = lv_obj_create(ui_Center);
    lv_obj_set_width(ui_grpVersorger, 416);
    lv_obj_set_height(ui_grpVersorger, 223);
    lv_obj_set_x(ui_grpVersorger, -14);
    lv_obj_set_y(ui_grpVersorger, 1);
    lv_obj_set_align(ui_grpVersorger, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_grpVersorger, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_grpVersorger, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_grpVersorger, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_grpVersorger, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_grpVersorger, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_grpVersorger);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 257);
    lv_obj_set_height(ui_Container2, 234);
    lv_obj_set_x(ui_Container2, 87);
    lv_obj_set_y(ui_Container2, 11);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel8 = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_Panel8, 269);
    lv_obj_set_height(ui_Panel8, 256);
    lv_obj_set_x(ui_Panel8, 7);
    lv_obj_set_y(ui_Panel8, 14);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel8, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0xFFCC88), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_Panel9, 242);
    lv_obj_set_height(ui_Panel9, 210);
    lv_obj_set_x(ui_Panel9, 26);
    lv_obj_set_y(ui_Panel9, 11);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel9, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_Panel10, 30);
    lv_obj_set_height(ui_Panel10, 26);
    lv_obj_set_x(ui_Panel10, -110);
    lv_obj_set_y(ui_Panel10, 111);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0xFFAA00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel10, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel11 = lv_obj_create(ui_grpVersorger);
    lv_obj_set_width(ui_Panel11, 112);
    lv_obj_set_height(ui_Panel11, 20);
    lv_obj_set_x(ui_Panel11, 105);
    lv_obj_set_y(ui_Panel11, -91);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ueberschriftmain = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_ueberschriftmain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ueberschriftmain, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ueberschriftmain, -16);
    lv_obj_set_y(ui_ueberschriftmain, -18);
    lv_label_set_text(ui_ueberschriftmain, "VersorgerBatterie");
    lv_obj_set_style_text_align(ui_ueberschriftmain, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ueberschriftmain, &ui_font_button, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statsmain = lv_obj_create(ui_grpVersorger);
    lv_obj_remove_style_all(ui_statsmain);
    lv_obj_set_width(ui_statsmain, 238);
    lv_obj_set_height(ui_statsmain, 197);
    lv_obj_set_x(ui_statsmain, 102);
    lv_obj_set_y(ui_statsmain, 9);
    lv_obj_set_align(ui_statsmain, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_statsmain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_voltagemain = lv_obj_create(ui_statsmain);
    lv_obj_remove_style_all(ui_voltagemain);
    lv_obj_set_width(ui_voltagemain, 100);
    lv_obj_set_height(ui_voltagemain, 61);
    lv_obj_clear_flag(ui_voltagemain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_voltagemain);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 3);
    lv_obj_set_y(ui_Label7, -4);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Voltage");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblvoltagemain = lv_label_create(ui_voltagemain);
    lv_obj_set_width(ui_lblvoltagemain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblvoltagemain, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblvoltagemain, 3);
    lv_obj_set_y(ui_lblvoltagemain, 21);
    lv_obj_set_align(ui_lblvoltagemain, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblvoltagemain, "24,2");
    lv_obj_set_style_text_font(ui_lblvoltagemain, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_voltagemain);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 27);
    lv_obj_set_y(ui_Label9, 21);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "V");
    lv_obj_set_style_text_font(ui_Label9, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_capacitymain = lv_obj_create(ui_statsmain);
    lv_obj_remove_style_all(ui_capacitymain);
    lv_obj_set_width(ui_capacitymain, 100);
    lv_obj_set_height(ui_capacitymain, 61);
    lv_obj_set_x(ui_capacitymain, 16);
    lv_obj_set_y(ui_capacitymain, 0);
    lv_obj_set_align(ui_capacitymain, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_capacitymain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_capacitymain);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 3);
    lv_obj_set_y(ui_Label8, -4);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Capacity");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblcapacitymain = lv_label_create(ui_capacitymain);
    lv_obj_set_width(ui_lblcapacitymain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblcapacitymain, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblcapacitymain, 3);
    lv_obj_set_y(ui_lblcapacitymain, 21);
    lv_obj_set_align(ui_lblcapacitymain, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblcapacitymain, "560");
    lv_obj_set_style_text_font(ui_lblcapacitymain, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_capacitymain);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 27);
    lv_obj_set_y(ui_Label10, 21);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "AH");
    lv_obj_set_style_text_font(ui_Label10, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempmain = lv_obj_create(ui_statsmain);
    lv_obj_remove_style_all(ui_tempmain);
    lv_obj_set_width(ui_tempmain, 100);
    lv_obj_set_height(ui_tempmain, 61);
    lv_obj_set_x(ui_tempmain, 0);
    lv_obj_set_y(ui_tempmain, -3);
    lv_obj_set_align(ui_tempmain, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_tempmain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_tempmain);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 3);
    lv_obj_set_y(ui_Label11, -4);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Temp");
    lv_obj_set_style_text_font(ui_Label11, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbltempmain = lv_label_create(ui_tempmain);
    lv_obj_set_width(ui_lbltempmain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbltempmain, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbltempmain, 3);
    lv_obj_set_y(ui_lbltempmain, 21);
    lv_obj_set_align(ui_lbltempmain, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbltempmain, "24,2");
    lv_obj_set_style_text_font(ui_lbltempmain, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_tempmain);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 27);
    lv_obj_set_y(ui_Label12, 21);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "C");
    lv_obj_set_style_text_font(ui_Label12, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_remainmain = lv_obj_create(ui_statsmain);
    lv_obj_remove_style_all(ui_remainmain);
    lv_obj_set_width(ui_remainmain, 100);
    lv_obj_set_height(ui_remainmain, 61);
    lv_obj_set_x(ui_remainmain, 0);
    lv_obj_set_y(ui_remainmain, -4);
    lv_obj_set_align(ui_remainmain, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_remainmain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_remainmain);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 3);
    lv_obj_set_y(ui_Label13, -4);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Remaining");
    lv_obj_set_style_text_font(ui_Label13, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblrmainmain = lv_label_create(ui_remainmain);
    lv_obj_set_width(ui_lblrmainmain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblrmainmain, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblrmainmain, 3);
    lv_obj_set_y(ui_lblrmainmain, 21);
    lv_obj_set_align(ui_lblrmainmain, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblrmainmain, "24,2");
    lv_obj_set_style_text_font(ui_lblrmainmain, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_remainmain);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 27);
    lv_obj_set_y(ui_Label14, 21);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "D");
    lv_obj_set_style_text_font(ui_Label14, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_grpMotor = lv_obj_create(ui_Center);
    lv_obj_set_width(ui_grpMotor, 416);
    lv_obj_set_height(ui_grpMotor, 223);
    lv_obj_set_x(ui_grpMotor, -14);
    lv_obj_set_y(ui_grpMotor, 1);
    lv_obj_set_align(ui_grpMotor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_grpMotor, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_grpMotor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_grpMotor, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_grpMotor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_grpMotor, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_grpMotor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_grpMotor);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 257);
    lv_obj_set_height(ui_Container3, 234);
    lv_obj_set_x(ui_Container3, 87);
    lv_obj_set_y(ui_Container3, 11);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel13 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_Panel13, 269);
    lv_obj_set_height(ui_Panel13, 256);
    lv_obj_set_x(ui_Panel13, 7);
    lv_obj_set_y(ui_Panel13, 14);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel13, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0xFFCC88), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel14 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_Panel14, 242);
    lv_obj_set_height(ui_Panel14, 210);
    lv_obj_set_x(ui_Panel14, 26);
    lv_obj_set_y(ui_Panel14, 11);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel14, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel15 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_Panel15, 30);
    lv_obj_set_height(ui_Panel15, 26);
    lv_obj_set_x(ui_Panel15, -110);
    lv_obj_set_y(ui_Panel15, 111);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel15, lv_color_hex(0xFFAA00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel15, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel16 = lv_obj_create(ui_grpMotor);
    lv_obj_set_width(ui_Panel16, 112);
    lv_obj_set_height(ui_Panel16, 20);
    lv_obj_set_x(ui_Panel16, 105);
    lv_obj_set_y(ui_Panel16, -91);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ueberschriftmotor = lv_label_create(ui_Panel16);
    lv_obj_set_width(ui_ueberschriftmotor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ueberschriftmotor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ueberschriftmotor, -14);
    lv_obj_set_y(ui_ueberschriftmotor, -18);
    lv_label_set_text(ui_ueberschriftmotor, "Starter Batterien");
    lv_obj_set_style_text_align(ui_ueberschriftmotor, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ueberschriftmotor, &ui_font_button, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statsmotor = lv_obj_create(ui_grpMotor);
    lv_obj_remove_style_all(ui_statsmotor);
    lv_obj_set_width(ui_statsmotor, 238);
    lv_obj_set_height(ui_statsmotor, 197);
    lv_obj_set_x(ui_statsmotor, 102);
    lv_obj_set_y(ui_statsmotor, 9);
    lv_obj_set_align(ui_statsmotor, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_statsmotor, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_voltagemaschine1 = lv_obj_create(ui_statsmotor);
    lv_obj_remove_style_all(ui_voltagemaschine1);
    lv_obj_set_width(ui_voltagemaschine1, 100);
    lv_obj_set_height(ui_voltagemaschine1, 61);
    lv_obj_clear_flag(ui_voltagemaschine1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel17 = lv_obj_create(ui_voltagemaschine1);
    lv_obj_set_width(ui_Panel17, 112);
    lv_obj_set_height(ui_Panel17, 18);
    lv_obj_set_x(ui_Panel17, 96);
    lv_obj_set_y(ui_Panel17, -39);
    lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ueberschriftmain3 = lv_label_create(ui_Panel17);
    lv_obj_set_width(ui_ueberschriftmain3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ueberschriftmain3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ueberschriftmain3, -16);
    lv_obj_set_y(ui_ueberschriftmain3, -18);
    lv_label_set_text(ui_ueberschriftmain3, "VersorgerBatterie");
    lv_obj_set_style_text_font(ui_ueberschriftmain3, &ui_font_button, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_voltagemaschine1);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, 3);
    lv_obj_set_y(ui_Label31, -4);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "Voltage 1");
    lv_obj_set_style_text_font(ui_Label31, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblvoltagemotor1 = lv_label_create(ui_voltagemaschine1);
    lv_obj_set_width(ui_lblvoltagemotor1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblvoltagemotor1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblvoltagemotor1, 3);
    lv_obj_set_y(ui_lblvoltagemotor1, 21);
    lv_obj_set_align(ui_lblvoltagemotor1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblvoltagemotor1, "24,2");
    lv_obj_set_style_text_font(ui_lblvoltagemotor1, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_voltagemaschine1);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, 27);
    lv_obj_set_y(ui_Label32, 21);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "V");
    lv_obj_set_style_text_font(ui_Label32, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempmaschine1 = lv_obj_create(ui_statsmotor);
    lv_obj_remove_style_all(ui_tempmaschine1);
    lv_obj_set_width(ui_tempmaschine1, 100);
    lv_obj_set_height(ui_tempmaschine1, 61);
    lv_obj_set_x(ui_tempmaschine1, 0);
    lv_obj_set_y(ui_tempmaschine1, -3);
    lv_obj_set_align(ui_tempmaschine1, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_tempmaschine1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label33 = lv_label_create(ui_tempmaschine1);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, 3);
    lv_obj_set_y(ui_Label33, -4);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "Temp 1");
    lv_obj_set_style_text_font(ui_Label33, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbltempmotor1 = lv_label_create(ui_tempmaschine1);
    lv_obj_set_width(ui_lbltempmotor1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbltempmotor1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbltempmotor1, 3);
    lv_obj_set_y(ui_lbltempmotor1, 21);
    lv_obj_set_align(ui_lbltempmotor1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbltempmotor1, "24,2");
    lv_obj_set_style_text_font(ui_lbltempmotor1, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_tempmaschine1);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, 27);
    lv_obj_set_y(ui_Label34, 21);
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "C");
    lv_obj_set_style_text_font(ui_Label34, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_voltagemaschine2 = lv_obj_create(ui_statsmotor);
    lv_obj_remove_style_all(ui_voltagemaschine2);
    lv_obj_set_width(ui_voltagemaschine2, 100);
    lv_obj_set_height(ui_voltagemaschine2, 61);
    lv_obj_set_x(ui_voltagemaschine2, 17);
    lv_obj_set_y(ui_voltagemaschine2, 0);
    lv_obj_set_align(ui_voltagemaschine2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_voltagemaschine2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label35 = lv_label_create(ui_voltagemaschine2);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, 3);
    lv_obj_set_y(ui_Label35, -4);
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, " Voltage 2");
    lv_obj_set_style_text_font(ui_Label35, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblvoltagemotor2 = lv_label_create(ui_voltagemaschine2);
    lv_obj_set_width(ui_lblvoltagemotor2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblvoltagemotor2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblvoltagemotor2, 3);
    lv_obj_set_y(ui_lblvoltagemotor2, 21);
    lv_obj_set_align(ui_lblvoltagemotor2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblvoltagemotor2, "24,2");
    lv_obj_set_style_text_font(ui_lblvoltagemotor2, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label36 = lv_label_create(ui_voltagemaschine2);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label36, 27);
    lv_obj_set_y(ui_Label36, 21);
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "V");
    lv_obj_set_style_text_font(ui_Label36, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempmaschine2 = lv_obj_create(ui_statsmotor);
    lv_obj_remove_style_all(ui_tempmaschine2);
    lv_obj_set_width(ui_tempmaschine2, 100);
    lv_obj_set_height(ui_tempmaschine2, 61);
    lv_obj_set_x(ui_tempmaschine2, 0);
    lv_obj_set_y(ui_tempmaschine2, -11);
    lv_obj_set_align(ui_tempmaschine2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_tempmaschine2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label37 = lv_label_create(ui_tempmaschine2);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, 3);
    lv_obj_set_y(ui_Label37, -4);
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "Temp 2");
    lv_obj_set_style_text_font(ui_Label37, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbltempmotor2 = lv_label_create(ui_tempmaschine2);
    lv_obj_set_width(ui_lbltempmotor2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbltempmotor2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbltempmotor2, 3);
    lv_obj_set_y(ui_lbltempmotor2, 21);
    lv_obj_set_align(ui_lbltempmotor2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbltempmotor2, "24,2");
    lv_obj_set_style_text_font(ui_lbltempmotor2, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label38 = lv_label_create(ui_tempmaschine2);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label38, 27);
    lv_obj_set_y(ui_Label38, 21);
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "C");
    lv_obj_set_style_text_font(ui_Label38, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_grpBug = lv_obj_create(ui_Center);
    lv_obj_set_width(ui_grpBug, 416);
    lv_obj_set_height(ui_grpBug, 223);
    lv_obj_set_x(ui_grpBug, -14);
    lv_obj_set_y(ui_grpBug, 1);
    lv_obj_set_align(ui_grpBug, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_grpBug, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_grpBug, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_grpBug, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_grpBug, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_grpBug, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_grpBug, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_grpBug);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 257);
    lv_obj_set_height(ui_Container4, 234);
    lv_obj_set_x(ui_Container4, 87);
    lv_obj_set_y(ui_Container4, 11);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel12 = lv_obj_create(ui_Container4);
    lv_obj_set_width(ui_Panel12, 269);
    lv_obj_set_height(ui_Panel12, 256);
    lv_obj_set_x(ui_Panel12, 7);
    lv_obj_set_y(ui_Panel12, 14);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel12, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0xFFCC88), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel18 = lv_obj_create(ui_Container4);
    lv_obj_set_width(ui_Panel18, 242);
    lv_obj_set_height(ui_Panel18, 210);
    lv_obj_set_x(ui_Panel18, 26);
    lv_obj_set_y(ui_Panel18, 11);
    lv_obj_set_align(ui_Panel18, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel18, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel18, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel18, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel19 = lv_obj_create(ui_Container4);
    lv_obj_set_width(ui_Panel19, 30);
    lv_obj_set_height(ui_Panel19, 26);
    lv_obj_set_x(ui_Panel19, -110);
    lv_obj_set_y(ui_Panel19, 111);
    lv_obj_set_align(ui_Panel19, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel19, lv_color_hex(0xFFAA00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel19, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel20 = lv_obj_create(ui_grpBug);
    lv_obj_set_width(ui_Panel20, 112);
    lv_obj_set_height(ui_Panel20, 20);
    lv_obj_set_x(ui_Panel20, 105);
    lv_obj_set_y(ui_Panel20, -91);
    lv_obj_set_align(ui_Panel20, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel20, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel20, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ueberschriftbug = lv_label_create(ui_Panel20);
    lv_obj_set_width(ui_ueberschriftbug, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ueberschriftbug, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ueberschriftbug, 2);
    lv_obj_set_y(ui_ueberschriftbug, -18);
    lv_label_set_text(ui_ueberschriftbug, "Bug Batterie");
    lv_obj_set_style_text_align(ui_ueberschriftbug, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ueberschriftbug, &ui_font_button, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statsbug = lv_obj_create(ui_grpBug);
    lv_obj_remove_style_all(ui_statsbug);
    lv_obj_set_width(ui_statsbug, 238);
    lv_obj_set_height(ui_statsbug, 197);
    lv_obj_set_x(ui_statsbug, 102);
    lv_obj_set_y(ui_statsbug, 9);
    lv_obj_set_align(ui_statsbug, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_statsbug, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_voltagebug = lv_obj_create(ui_statsbug);
    lv_obj_remove_style_all(ui_voltagebug);
    lv_obj_set_width(ui_voltagebug, 100);
    lv_obj_set_height(ui_voltagebug, 61);
    lv_obj_clear_flag(ui_voltagebug, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel21 = lv_obj_create(ui_voltagebug);
    lv_obj_set_width(ui_Panel21, 112);
    lv_obj_set_height(ui_Panel21, 18);
    lv_obj_set_x(ui_Panel21, 96);
    lv_obj_set_y(ui_Panel21, -39);
    lv_obj_set_align(ui_Panel21, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel21, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel21, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ueberschriftmain4 = lv_label_create(ui_Panel21);
    lv_obj_set_width(ui_ueberschriftmain4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ueberschriftmain4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ueberschriftmain4, -16);
    lv_obj_set_y(ui_ueberschriftmain4, -18);
    lv_label_set_text(ui_ueberschriftmain4, "VersorgerBatterie");
    lv_obj_set_style_text_font(ui_ueberschriftmain4, &ui_font_button, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_voltagebug);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 3);
    lv_obj_set_y(ui_Label15, -4);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Voltage");
    lv_obj_set_style_text_font(ui_Label15, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblvoltagebug = lv_label_create(ui_voltagebug);
    lv_obj_set_width(ui_lblvoltagebug, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblvoltagebug, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblvoltagebug, 3);
    lv_obj_set_y(ui_lblvoltagebug, 21);
    lv_obj_set_align(ui_lblvoltagebug, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblvoltagebug, "24,2");
    lv_obj_set_style_text_font(ui_lblvoltagebug, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_voltagebug);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 27);
    lv_obj_set_y(ui_Label16, 21);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "V");
    lv_obj_set_style_text_font(ui_Label16, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempbug = lv_obj_create(ui_statsbug);
    lv_obj_remove_style_all(ui_tempbug);
    lv_obj_set_width(ui_tempbug, 100);
    lv_obj_set_height(ui_tempbug, 61);
    lv_obj_set_x(ui_tempbug, 0);
    lv_obj_set_y(ui_tempbug, -3);
    lv_obj_set_align(ui_tempbug, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_tempbug, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_tempbug);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 3);
    lv_obj_set_y(ui_Label17, -4);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Temp 1");
    lv_obj_set_style_text_font(ui_Label17, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbltempbug = lv_label_create(ui_tempbug);
    lv_obj_set_width(ui_lbltempbug, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbltempbug, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbltempbug, 3);
    lv_obj_set_y(ui_lbltempbug, 21);
    lv_obj_set_align(ui_lbltempbug, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbltempbug, "24,2");
    lv_obj_set_style_text_font(ui_lbltempbug, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_tempbug);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 27);
    lv_obj_set_y(ui_Label18, 21);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "C");
    lv_obj_set_style_text_font(ui_Label18, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Background);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 144);
    lv_obj_set_height(ui_Container1, 221);
    lv_obj_set_x(ui_Container1, 154);
    lv_obj_set_y(ui_Container1, -2);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel6 = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_Panel6, 146);
    lv_obj_set_height(ui_Panel6, 152);
    lv_obj_set_x(ui_Panel6, 0);
    lv_obj_set_y(ui_Panel6, 60);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0xFF8866), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_Panel2, 113);
    lv_obj_set_height(ui_Panel2, 150);
    lv_obj_set_x(ui_Panel2, -8);
    lv_obj_set_y(ui_Panel2, 69);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_Panel7, 23);
    lv_obj_set_height(ui_Panel7, 22);
    lv_obj_set_x(ui_Panel7, -121);
    lv_obj_set_y(ui_Panel7, 122);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0xFF8800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel7, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttons = lv_obj_create(ui_Background);
    lv_obj_remove_style_all(ui_buttons);
    lv_obj_set_width(ui_buttons, 152);
    lv_obj_set_height(ui_buttons, 166);
    lv_obj_set_x(ui_buttons, 11);
    lv_obj_set_y(ui_buttons, 45);
    lv_obj_set_align(ui_buttons, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_buttons, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnbug = lv_btn_create(ui_buttons);
    lv_obj_set_width(ui_btnbug, 82);
    lv_obj_set_height(ui_btnbug, 32);
    lv_obj_set_x(ui_btnbug, -30);
    lv_obj_set_y(ui_btnbug, 10);
    lv_obj_set_align(ui_btnbug, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnbug, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnbug, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnbug, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnbug, lv_color_hex(0xCC4444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnbug, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnbug, lv_color_hex(0xFF5555), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btnbug, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label4 = lv_label_create(ui_btnbug);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 17);
    lv_obj_set_y(ui_Label4, 5);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Bug");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_button, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnmotor = lv_btn_create(ui_buttons);
    lv_obj_set_width(ui_btnmotor, 82);
    lv_obj_set_height(ui_btnmotor, 32);
    lv_obj_set_x(ui_btnmotor, -30);
    lv_obj_set_y(ui_btnmotor, -25);
    lv_obj_set_align(ui_btnmotor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnmotor, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnmotor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnmotor, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnmotor, lv_color_hex(0xFF9966), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnmotor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnmotor, lv_color_hex(0xFFAA90), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btnmotor, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label3 = lv_label_create(ui_btnmotor);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 12);
    lv_obj_set_y(ui_Label3, 4);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Motor");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_button, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnmain = lv_btn_create(ui_buttons);
    lv_obj_set_width(ui_btnmain, 82);
    lv_obj_set_height(ui_btnmain, 32);
    lv_obj_set_x(ui_btnmain, -30);
    lv_obj_set_y(ui_btnmain, -60);
    lv_obj_set_align(ui_btnmain, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnmain, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnmain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnmain, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnmain, lv_color_hex(0xFF8800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnmain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnmain, lv_color_hex(0xFFAA00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btnmain, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label5 = lv_label_create(ui_btnmain);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 3);
    lv_obj_set_y(ui_Label5, 4);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Versorger");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_button, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Background);
    lv_obj_set_width(ui_Panel4, 59);
    lv_obj_set_height(ui_Panel4, 34);
    lv_obj_set_x(ui_Panel4, -244);
    lv_obj_set_y(ui_Panel4, -71);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFAA00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel4, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 3);
    lv_obj_set_y(ui_Label2, 13);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Kassiopeia");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_sidebar, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Background);
    lv_obj_set_width(ui_Panel1, 59);
    lv_obj_set_height(ui_Panel1, 60);
    lv_obj_set_x(ui_Panel1, -244);
    lv_obj_set_y(ui_Panel1, -21);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xCC4444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel1, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTime = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_lblTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTime, 15);
    lv_obj_set_y(ui_lblTime, 23);
    lv_obj_set_align(ui_lblTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTime, "24:59");
    lv_obj_set_style_text_color(ui_lblTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTime, &ui_font_sidebar, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Background);
    lv_obj_set_width(ui_Panel3, 59);
    lv_obj_set_height(ui_Panel3, 34);
    lv_obj_set_x(ui_Panel3, -244);
    lv_obj_set_y(ui_Panel3, 26);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFAA90), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel3, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgchargetrans = lv_img_create(ui_Panel3);
    lv_img_set_src(ui_imgchargetrans, &ui_img_charge_trans_png);
    lv_obj_set_width(ui_imgchargetrans, LV_SIZE_CONTENT);   /// 59
    lv_obj_set_height(ui_imgchargetrans, LV_SIZE_CONTENT);    /// 34
    lv_obj_set_align(ui_imgchargetrans, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgchargetrans, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgchargetrans, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgcharge = lv_img_create(ui_Panel3);
    lv_img_set_src(ui_imgcharge, &ui_img_charge_png);
    lv_obj_set_width(ui_imgcharge, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgcharge, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgcharge, 2);
    lv_obj_set_y(ui_imgcharge, 2);
    lv_obj_set_align(ui_imgcharge, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgcharge, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgcharge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel5 = lv_obj_create(ui_Background);
    lv_obj_set_width(ui_Panel5, 59);
    lv_obj_set_height(ui_Panel5, 34);
    lv_obj_set_x(ui_Panel5, -244);
    lv_obj_set_y(ui_Panel5, 60);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xFFAA00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel5, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Panel5);
    lv_img_set_src(ui_Image1, &ui_img_blitz_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, -14);
    lv_obj_set_y(ui_Image1, 8);
    lv_obj_set_align(ui_Image1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_socmain = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_socmain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_socmain, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_socmain, 14);
    lv_obj_set_y(ui_socmain, 7);
    lv_obj_set_align(ui_socmain, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_socmain, "100%");
    lv_obj_set_style_text_color(ui_socmain, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_socmain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_socmain, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_socmain, &ui_font_battery, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnbug, ui_event_btnbug, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnmotor, ui_event_btnmotor, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnmain, ui_event_btnmain, LV_EVENT_ALL, NULL);

}
